#ifndef DEMONSTRATION_H_INCLUDED
#define DEMONSTRATION_H_INCLUDED
#include <iostream>
#include <windows.h>
using namespace std;
void DEMONSTRATION()
{
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Demonstration"<<endl<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Benchmark";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"MAIN MENU\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Interactive"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Demonstration"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Benchmark";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Add a circle";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"    <--"<<(char) 253<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle"<<endl<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    cout<<"Enter X coordinate of the circle             <ESC to go back>\n";
    Sleep(300);
    cout<<1;
    Sleep(200);
    cout<<3;
    Sleep(130);
    cout<<endl<<"Enter Y coordinate of the circle             <ESC to go back>"<<endl;
    Sleep(300);
    cout<<'-';
    Sleep(200);
    cout<<7;
    Sleep(130);
    cout<<endl<<"Enter RADIUS of the circle             <ESC to go back>"<<endl;
    Sleep(300);
    cout<<4;
    Sleep(200);
    cout<<2;
    Sleep(1300);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);

    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"    <--"<<(char)253<<"\nAdd a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    cout<<"\n\n"<<(char)252<<"   X   Y   Radius\n1   13   -23   42\nPress any key to continue";
    Sleep(1500);

    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    Sleep(600);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    Sleep(600);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Delete circle";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    Sleep(600);

    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Delete circle";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<< "   <--"<<(char)253<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    cout<<"\n\n"<<"Chose circle to delete\n"<<(char)252<<"   X   Y   Radius\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"1   13   -23   42";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),6);
    cout<<endl<<"To go back press ESC";
    Sleep(2200);

    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    Sleep(600);
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    system("cls");
    cout<<"INTERACTIVE MODE\n";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),115);
    cout<<"Show all circles";
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"   <--"<<(char)253<<endl;
    cout<<"Add a circle"<<endl;
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3);
    cout<<"Delete circle";
    cout<<endl<<endl;

    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15);
    cout<<"No circles";
    Sleep(1500);

}

#endif // DEMONSTRATION_H_INCLUDED
